name: multi-job workflow
on: [push]

jobs:
  name: ubuntu
    runs-on: ubuntu-latest
    - name: Checkout code
    uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.5.0
      with:
        go-version: "1.20"

    - name: Build Go binary
      run: go build -o main main.go

    - name: Run binary
      run: ./main

  name: windows
    runs-on: windows-latest
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.5.0
      with:
        go-version: "1.20"

    - name: Build Go binary
      run: go build -o main.exe main.go

    - name: Run binary
      run: .\main.exe

  name: macos
    runs-on: macos-latest
    - name: Checkout code
    uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5.5.0
      with:
        go-version: "1.20"

    - name: Build Go binary
      run: go build -o main main.go

    - name: Run binary
      run: ./main

  name: cross-compile
    runs-on: ubuntu-latest
    needs: [ubuntu, windowa, macos]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version: "1.20"

      - name: Cross-compile for all platforms
        run: |
          echo "Cross compiling for all platforms:"
          GOOS=linux GOARCH=amd64 go build -o main-linux main.go
          GOOS=windows GOARCH=amd64 go build -o main-windows.exe main.go
          GOOS=darwin GOARCH=amd64 go build -o main-macos-intel main.go